config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :bookings

  root 'bookings#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :destroy, Booking, user_id: user.id
    can :update, Booking, user_id: user.id
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  belongs_to :user

  validates :description, :date, :time, presence: true
  validates :date, uniqueness: {
    scope: :time, message: I18n.t('.errors.messages.already_reserved')
  }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_url, alert: I18n.t('.pages.unathorized_action')
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  respond_to :html, :js

  before_action :authenticate_user!
  before_action :set_booking, only: %i[edit update show destroy]

  def index
    @bookings_presenter = BookingsPresenter.new(
      Booking.order(date: :asc),
      params[:date] || Date.today
    )
  end

  def new
    @booking = current_user.bookings.new
  end

  def create
    @booking = current_user.bookings.create(booking_params)

    respond_with @booking, location: bookings_path
  end

  def show; end

  def edit
    authorize! :update, @booking
  end

  def update
    authorize! :update, @booking
    @booking.update(booking_params)

    respond_with @booking, location: bookings_path
  end

  def destroy
    authorize! :destroy, @booking

    @booking.destroy
    respond_with @booking, location: bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :time, :description)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(key)
    case key.to_s
    when 'notice'
      'success'
    when 'alert'
      'danger'
    else
      'default'
    end
  end
end

app/views/bookings/_bookings.html.erb
<div class="card card-body bg-light mb-3">
  <div class="button-group mx-auto small">
    <%= link_to  @bookings_presenter.previous_link, class: 'btn btn-sm btn-primary', remote: true, id: 'previous_week' do %>
      <i class="fas fa-arrow-left"></i>
    <% end %>

    <b>
      <%= link_to 'VER SEMANA ATUAL', @bookings_presenter.current_week_link,
      class: 'btn btn-sm btn-secondary currentWeekButton', remote: true, id: 'current_week' %>
    </b>

    <%= link_to @bookings_presenter.next_link, class: 'btn btn-sm btn-primary text-right', remote: true, id: 'next_week' do %>
      <i class="fas fa-arrow-right"></i>
    <% end %>
  </div>
</div>

<table class="table table-bordered">
  <thead>
    <th>Horário</th>
    <% (@bookings_presenter.beginning_of_week..@bookings_presenter.end_of_week).each do |day| %>
      <th class="text-center">
        <%= I18n.t(day.strftime('%A').downcase, scope: [:date, :day_names]) %>
        <small>(<%= l(day) %>)</small>
      </th>
    <% end %>
  </thead>
  <tbody>
    <% @bookings_presenter.listable_hours.each do |hour| %>
      <tr>
        <td class="text-center"><%= hour %></td>
        <% (@bookings_presenter.beginning_of_week..@bookings_presenter.end_of_week).each_with_index do |day, index| %>
          <% if booking = @bookings_presenter.records.find_by(date: day, time: hour) %>
            <td class="text-center nowrap">
              <% if can?(:update, booking) %>
                <%= link_to (raw @bookings_presenter.reservation_text(booking)), edit_booking_path(booking),
                    remote: true, class: 'reservedLink', id: "edit-#{booking.id}" %>
                <% else %>
                  <%= link_to (raw @bookings_presenter.reservation_text(booking)), booking_path(booking),
                      remote: true, class: 'reservedLink', id: "show-#{booking.id}" %>
                <% end %>

              <% if can?(:destroy, booking) %>
                <%= link_to booking_path(booking), method: :delete, remote: true, class: 'destroyLink',
                    id: "destroy-#{booking.id}", data: { confirm: 'Tem certeza?' } do %>
                  <span><i class="fas fa-redo"></i></span>
                <% end %>
              <% end %>
            </td>
          <% else %>
            <td class="text-center">
              <%= @bookings_presenter.availability_text(day, hour) %>
            </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/_form.html.erb
<%= simple_form_for @booking, remote: true do |f| %>
  <div class="modal-body">
    <div id="errors"></div>

    <p class="small"><b>Data: </b><%= l(@booking.date || params[:date].to_date) %></p>
    <%= f.input :date, as: :hidden, input_html: { value: @booking.date || params[:date] } %>

    <p class="small"><b>Hora: </b><%= @booking.time&.strftime('%H:%M') || params[:time] %></p>
    <%= f.input :time, as: :hidden, input_html: { value: @booking.time || params[:time] } %>

    <%= f.input :description, required: true, input_html: { class: 'form-control' } %>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Fechar</button>
    <%= f.button :submit, class: 'btn btn-primary btn-sm', data: { disable_with: 'Salvando...' } %>
  </div>
<% end %>

app/views/bookings/_show.html.erb
<div class="modal-body">
  <p class="small"><b>Data: </b><%= l(@booking.date) %></p>
  <p class="small"><b>Horário: </b><%= @booking.time.strftime('%H:%M') %></p>
  <p class="small"><b>Descrição: </b><%= @booking.description %></p>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Fechar</button>
</div>

app/views/bookings/create.js.erb
<% if @booking.errors.any? %>
  $('#errors').html("<%= j render('shared/errors', resource: @booking) %>");
<% else %>
  $('#modal').modal('hide');
  $.notify({ message: 'Reserva realizada com sucesso.' }, { type: 'success' });

  $.ajax({
    url: "/bookings?date=<%= @booking.date %>",
    dataType: 'script'
  });
<% end %>

app/views/bookings/destroy.js.erb
<% if @booking.destroyed? %>
  $.notify({ message: 'Reserva deletada com sucesso.' }, { type: 'success' });

  $.ajax({
    url: "/bookings?date=<%= @booking.date %>",
    dataType: 'script'
  });
<% end %>

app/views/bookings/edit.js.erb
$('#modalTitle').html('Editar Reserva');
$('#modalBody').html("<%= j render('form') %>");
$('#modal').modal();

app/views/bookings/index.html.erb
<h1 class="mb-3">Reserva de Sala</h1>

<div id="bookings">
  <%= render 'bookings' %>
</div>

<%= render 'shared/modal' %>

app/views/bookings/index.js.erb
$('#bookings').html("<%= j render('bookings') %>");

app/views/bookings/new.js.erb
$('#modalTitle').html('Reservar Sala');
$('#modalBody').html("<%= j render('form') %>");
$('#modal').modal();

app/views/bookings/show.js.erb
$('#modalTitle').html('Detalhes da reserva');
$('#modalBody').html("<%= j render('show') %>");
$('#modal').modal();

app/views/bookings/update.js.erb
<% if @booking.errors.any? %>
  $('#errors').html("<%= j render('shared/errors', resource: @booking) %>");
<% else %>
  $('#modal').modal('hide');
  $.notify({ message: 'Reserva atualizada com sucesso.' }, { type: 'success' });

  $.ajax({
    url: "/bookings?date=<%= @booking.date %>",
    dataType: 'script'
  });
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' if current_user %>

    <div class="container" id="main">
      <%= render 'shared/flash' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger small" id="alert-errors">
    <% resource.errors.full_messages.each do |msg| %>
      <div style="line-height:17px;"><%= raw msg %></div>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% for key, msg in flash %>
  <% flash_class = flash_class(key) %>
  <div>
    <div class="alert alert-<%= flash_class %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%= msg %>
    </div>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal" tabindex="-1" id="modal" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 id='modalTitle' class="modal-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="modalBody"></div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </li>
    </ul>
  </div>
</nav>